# Dockerfile.web
FROM python:3.12-slim

WORKDIR /app

COPY streamlit_app/ streamlit_app/
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]